export const AUDIT_ACTIONS = {
  // Admin
  ADMIN_BOOTSTRAPPED: 'ADMIN_BOOTSTRAPPED',
  
  // Auth
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  
  // Users
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  
  // Clients
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_DELETED: 'CLIENT_DELETED',
  
  // Services
  SERVICE_CREATED: 'SERVICE_CREATED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  SERVICE_DELETED: 'SERVICE_DELETED',
  
  // Professionals
  PROFESSIONAL_CREATED: 'PROFESSIONAL_CREATED',
  PROFESSIONAL_UPDATED: 'PROFESSIONAL_UPDATED',
  PROFESSIONAL_DELETED: 'PROFESSIONAL_DELETED',
  
  // Appointments
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_STATUS_CHANGED: 'APPOINTMENT_STATUS_CHANGED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  
  // Queue
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_CALLED: 'TICKET_CALLED',
  TICKET_SERVED: 'TICKET_SERVED',
  TICKET_DONE: 'TICKET_DONE',
  TICKET_CANCELLED: 'TICKET_CANCELLED',
  DESK_ASSIGNED: 'DESK_ASSIGNED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITIES = {
  USER: 'user',
  CLIENT: 'client',
  SERVICE: 'service',
  PROFESSIONAL: 'professional',
  APPOINTMENT: 'appointment',
  QUEUE_TICKET: 'queue_ticket',
  DESK: 'desk',
} as const;

export type AuditEntity = (typeof AUDIT_ENTITIES)[keyof typeof AUDIT_ENTITIES];
